spring.application.name=aitracker

app.encryption.key=T3kFLvZ3jd0cCHwo86oGr478LCZHpUTo4cX4byAiTkQ=

spring.datasource.url=jdbc:postgresql://ep-calm-block-apn111uo-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080